blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Nitro Documentation
    url: https://nitro.unjs.io/
    about: Check the documentation for usage of Nuxt 3
  - name: ðŸ’¬ Discussions
    url: https://github.com/unjs/nitro/discussions
    about: Use discussions if you have an idea for improvement and asking questions
  - name: ðŸ”— Nuxt related Issues
    url: https://github.com/nuxt/nuxt/issues/new/choose
    about: Please open an issue in nuxt/nuxt to discuss
